notify-update: true
deaths:
  # if false permission: 'essentials.event.death.location'
  send-location: true
  drop-player-head:
    # enable drop player heads
    enable: true
    # chance of the drop
    chance: 30
economy:
  currency: "$"
  format: "#,##0.00"
  starter-balance: 0.0
  minimum-payment: 0.01
homes:
  # if player has permission: 'essentials.command.sethome.multiple.default'
  default: 3
  vip: 6
  staff: 12
commands:
  rtp:
    world: world
    spread: 1250
  cooldown:
    # cooldown for rank commands
    # these are the only ones which are able to get cooldown
    feed: 120
    heal: 120
    repair: 3600
    rtp: 3600
  disable:
    - icanhasbukkit
    - version
    - about
    - me
    - stop
    - reload
connection:
  join:
    # if false permission: 'essentials.event.join.message'
    enable: true
    message: "%player%&e has joined the server [&a+&e]"
    sound:
      enable: true
      type: ENTITY_FOX_AMBIENT
      volume: 0.75
      pitch: 1.0
  quit:
    # if false permission: 'essentials.event.quit.message'
    enable: true
    message: "%player%&e has left the server [&c-&e]"
    sound:
      enable: true
      type: ENTITY_FOX_AMBIENT
      volume: 0.75
      pitch: 1.0
help:
  - "&6Help:"
  - "- https://store.your-server.org/help"
message-of-the-day:
  welcome:
    - "&6Welcome&f %player%&6 to the server!"
  welcome-back:
    - "&6Welcome back&f %player%"
    - "&6We missed you!"
notification:
  # Permissions
  # essentials.event.block-break.notify
  # essentials.event.bucket-empty.notify
  # essentials.event.block-place.notify
  #
  # Placeholders
  # {0} Player, {1} Material
  # {2} World, {3} X, {4} Y, {5} Z
  enable: false
  block-break:
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
    - EMERALD_ORE
    - DEEPSLATE_EMERALD_ORE
    - ANCIENT_DEBRIS
  bucket-empty:
    - LAVA_BUCKET
  block-place:
    - TNT
  message:
    - "&7---------------"
    - "&cDetected: &f{0}"
    - "&cMaterial: &f{1}"
    - "&cLocation:"
    - "&cWorld:&f {2} &cX: &f{3} &cY: &f{4} &cZ: &f{5}"
    - "&7---------------"
physics:
  disable-tramping-farmland: true
  disable-tramping-turtle-egg: true
  disable-tramping-sniffer-egg: true
rules:
  - "&6Rules:"
  - "&61.&f No server crashing"
  - "&62.&f No griefing"
  - "&63.&f No Monkieng around! uhh?"
scale:
  max: 1.0
  minimum: 0.25
store:
  - "&6Store:"
  -  "- https://store.your-server.org"
teleport:
  delay: 3
  cancel-on-damage: true
  cancel-on-move: true
portal:
  enable: false
  spawn:
    NETHER: world
    END: world_the_end
